# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66c6dbec35d483f71f3933b05ebccc00afc2fa843be60d37ffd9b75d9220bba5e41a0d704b94f97f0908bf8ebd78c028ed010b44de638664fe039f8cef4a828

test:
  secret_key_base: e4f31ac1311dec3eca5caf784132312f3155d23f0c8a5e94d52b0ea9138aeb24db6bb72f3e825a12a731785c7700a11695ae6bcc9638b92371a792b08caddfa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
